

export enum AuditAction {
    // Auth
    USER_REGISTER = "USER_REGISTER",
    LOGIN_SUCCESS = "LOGIN_SUCCESS",
    LOGIN_FAILED_USER_NOT_FOUND = "LOGIN_FAILED_USER_NOT_FOUND",
    LOGIN_FAILED_INVALID_PASSWORD = "LOGIN_FAILED_INVALID_PASSWORD",
    LOGOUT = "LOGOUT",

    // Tasks
    TASK_CREATED = "TASK_CREATED",
    TASK_UPDATED = "TASK_UPDATED",
    TASK_DELETED = "TASK_DELETED",

    // Task Assignment
    TASK_ASSIGNED = "TASK_ASSIGNED",
    TASK_UNASSIGNED = "TASK_UNASSIGNED",

    // Projects
    PROJECT_CREATED = "PROJECT_CREATED",
    PROJECT_UPDATED = "PROJECT_UPDATED",
    PROJECT_DELETED = "PROJECT_DELETED",
    PROJECT_RESTORED = "PROJECT_RESTORED",
}