export enum Permission {
  ASSIGN_TASK = 'assign_task',
  UNASSIGN_TASK = 'unassign_task',
  VIEW_TASK_ASSIGNMENTS = 'view_task_assignments',
  TRANSFER_OWNERSHIP = 'transfer_ownership',
  BULK_ASSIGN_USERS = 'bulk_assign_users',
  REMOVE_USER_FROM_TASK = 'remove_user_from_task',
  GET_USER_ASSIGNED_TASKS = 'get_user_assigned_tasks',
  GET_ASSIGNMENTS_FOR_OTHER_USER = 'get_assignments_for_other_user',
  UPDATE_PERMISSION = 'update_permission',
  GET_USER_TASK_PERMISSION = 'get_user_task_permission',
  GET_ALL_USERS_PERMISSIONS = 'get_all_users_permissions',
  GET_ALL_TASKS_PERMISSIONS = 'get_all_tasks_permissions',
  GET_ALL_ASSIGNMENTS = 'get_all_assignments',
  GET_ALL_TASKS_ASSIGNMENTS = 'get_all_tasks_assignments',
}
